### ISSUE TITLE
Problem with filenames in zip - Linux - With solution

### ISSUE THREAD

**Issue by Valerie-Kyrie** [jan-bures/UitkForKsp2#5]
I have been trying to get BepInEx to work with SpaceWarp, however, UitkForKsp2 has an easily corrected issue on my Linux PC which SpaceWarp requires as a dependency.

When I download UitkForKSP2 the filenames and directories they are in are incorporated into the filenames.
I.E.
the file "UnityEngine.UIElementsModule.dll" located in "BepInEx\plugins\UitkForKsp2\lib\" has the filename
"BepInEx\plugins\UitkForKsp2\lib\UnityEngine.UIElementsModule.dll"

I am unsure why this .zip extracts this way, and only this compressed .zip from what I have found.

To fix this issue and make SpaceWarp work.. Rebuild the directory structure and name the file correctly.

Create the missing directories (case sensitive) and copy the files with that directory structure in the name to the appropriate location:
BepInEx
BepInEx/patchers
BepInEx/patchers/UitkForKsp2.Patcher
BepInEx/plugins
BepInEx/plugins/lib
BepInEx/plugins/assets

Remember to rename the files, removing the unneeded directory structure from the filenames.

Once this is completed. install as normal into your Kerbal Space Program 2 directory and run the KSP2_x64.exe through Proton.

Hopefully this helps someone else. :)

**Comment by jan-bures** [comment]
Thanks for bringing this to my attention, I know exactly where the issue is, but not sure just yet how to best fix it. (I assume) this happens because I am using PowerShell to zip the files in release mode, and apparently that generates the zip paths in the Windows format (with backslash characters - `\`), which it seems doesn't get extracted properly on Linux (though it might depend on the specific software use to extract the files).

The previous approach I used for this was the built-in MSBuild task `ZipDirectory`, which in turn generated files that CKAN was unable to extract, due to a checksum mismatch or something related.

I'll have to think about how to best solve this, preferably without having to involve some third-party zip tool in the build process.

**Comment by jan-bures** [comment]
This should hopefully be solved with the current version, and all upcoming ones. Thank you for reporting it!
